version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=eveeze
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=eveeze_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
